name: Node.js CI

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: #for Create release branch
      contents: write

    steps:    
    - name: Checkout code
      uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Create configuration file
      run: |
        echo "RECONNECT_TRIES=${{ secrets.RECONNECT_TRIES }} 
        SERVER_URL=${{ secrets.SERVER_URL }}
        VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }}
        CURRENT_TAG=${{ env.TAG }}" > .env
      working-directory: ./web

    - name: Install Vercel CLI
      run: npm install --global vercel@canary
      working-directory: ./web

    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

    - name: Build Project Artifacts
      run: |
        vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

    - name: Deploy Project Artifacts to Vercel
      run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}